services:
  # frontend:
  #     build:
  #       context: ./src/frontend
  #       dockerfile: Dockerfile
  #     ports:
  #       - "5000:5000"
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    env_file:
      - src/backend/.env
volumes:
  db_data:
